### ISSUE TITLE
Decorating views

### ISSUE THREAD

**Issue by nicoddemus** [rougeth/bottery#102]
How about we use decorators instead of having an explicit registry?

```python
# quick example of a ping pong bot
from bottery.conf.patterns import DefaultPattern, Pattern

@Pattern('ping')
def pong(message):
    return "pong!"

@DefaultPattern
def not_found(message):
    return "Sorry, I didn't understand you :/"
```

**Comment by guidiego** [comment]
@nicoddemus  Correct me if I am wrong, but to use this guys in that way, we will need to have a global var inside `bottery.conf.patterns`, or make a kind of filter using a property inside the function. Isn't better do something like: 


```python 

from bottery.conf.patterns import BotPatterns

bp = BotPatterns()

@bp.Pattern('ping')
def pong(message):
    return "pong!"

@bp.DefaultPattern
def not_found(message):
    return "Sorry, I didn't understand you :/"

patterns = bp.get_patterns()
```

This approach open space to insert params in `get_patterns()` and `BotPatterns()` call :)

**Comment by nicoddemus** [comment]
Hey @guidiego! 

> Correct me if I am wrong, but to use this guys in that way, we will need to have a global var inside bottery.conf.patterns

Yes, but very much as we have a `patterns` global variable now 😉 

> make a kind of filter using a property inside the function

You mean make the decorator add an attribute to the decorated function (`func._bottery_pattern = True`) and then we just `dir()` the module and get all functions with that attribute set? Yes that's another possibility.

Your `BotPatterns()` suggestion is good, but complicates usage a little bit I think... do we have an idea of a custom configuration for a set of patterns we could have?

FWIW I like the "decorated attribute" approach (but not by a large margin), but we might want to decide first if we want to have this API before delving too deep into the implementation.

**Comment by guidiego** [comment]
@nicoddemus like your comment!

> do we have an idea of a custom configuration for a set of patterns we could have?

Maybe some whatsaap and github stuff as well. Slack, Telegram e Messenger are the only 3 platforms that I know that support buttons, and custom stuffs in body. We can have a option to doesn't sent a kind of message to unsupported platforms, or, to use a custom parser.

Another good point about decorators (we can open another issue for it), is if one day we decided to go to this kind of approach:

```python

@bottery.Pattern('ping')
class MyView():
     def parser():
          # return basic_parser
     def telegram_parser():
          # return message for telegram
     def slack_parser():
          # return message for slack

```

Today I Implement a class called Response, that receive the parsed message as attributes: 
https://github.com/rougeth/bottery/pull/78

**Comment by nicoddemus** [comment]
Howdy @guidiego! 

> Maybe some whatsaap and github stuff as well. Slack, Telegram e Messenger are the only 3 platforms that I know that support buttons, and custom stuffs in body. We can have a option to doesn't sent a kind of message to unsupported platforms, or, to use a custom parser.

I'm not sure how this comment maps to a *set* of patterns, which is what I understood from your earlier example:

```
bp = BotPatterns()
bp._custom_config = 'bleh'
```

Can you provide an example what you mean by "support buttons" in this case? And why it would be a good idea to have this defined in different `BotPatterns`? Perhaps that will clarify things for me.

About your class decorator example, I believe having different ways to parse bodies was one of the benefits of having explicit `Pattern` classes (like `RegexPattern`, `NTLPattern`, etc), although I don't think they do anything about parsing the response from the view.

**Comment by guidiego** [comment]
Sure that I can @nicoddemus, lets start with a example:

```python
from bottery.conf.patterns import Pattern
from bottery.response import Response
from bottery.widget.telegram import telegram_response, reply_keyboard_markup

def pong(message):
    telegram_kb = reply_keyboard_markup([['First'], ['Second']])
    telegram = telegram_response(message.user.id, 'test', reply_markup=telegram_kb)

    return Response(telegram=telegram)

patterns = [
    Pattern('ping', pong),
]
```

In #78 this is how I insert custom keyboard buttons on telegram response. Let's imagine that one day we will do something like that for Slack or Messenger. I my mind bottery wants to be a easy way to do that cross-platform bots, so I need to understand that `telegram.reply_keyboard_markup` is similar to an another widget in other platform, something like `slack.foo_bar_reactions` and both represents something like `default.keyboard_custom`. Once that I add `default.keyboard_custom`, I will call `telegram.reply_keyboard_markup` to telegram response and `slack.foo_bar_reactions` to slack one. But let's imagine that I have a whatsapp message to be delivered too, and whatsapp didn't support this kind of addon, so I have 2 options: 

1 - Create a custom parser (add some more text to receive the options in other hand)
2 - Omit the message

In `BotPatterns()` approach we can use something like:

```
bp = BotPatterns()
bp._whatsapp.omit = #logic
bp._whatsapp.widget.keyboard_custom = customImplementation
```

**Comment by rougeth** [comment]
@guidiego In your example, you'll want that the bot respond or act in some way depending on which button the user clicked, right? If whatspp doesn't implement that kind of button, there is no way to continue the flow like telegram, so, we would need two different views. 

I believe that trying to make this relations on features that each platform implement will be something really hard to do and maybe out of our scope.

**Comment by leportella** [comment]
I think that after the refactor this issue should be closed, since patterns changed drastically
