### ISSUE TITLE
run bottery in production

### ISSUE THREAD

**Issue by romulocollopy** [rougeth/bottery#129]
I'd like to discuss how is the best way to deploy Bottery.

It is already possible to run bottery as a python command in  uWsgi
```sh
$ uwsgi --http :8000 --py bot.py --master --processes 4 --threads 3 
```
or with gunicorn and `aiohttp.worker.GunicornWebWorker`

```sh
$ gunicorn bot:bot.server -b 127.0.0.1:8000 --worker-class aiohttp.worker.GunicornWebWorker
```

In booth cases, `bot.run(server_port=7000)` is called to start and configure Bottery.
Maybe we could extract part of `run`method for someting called `start_app` to avoid some unnecessary calls, as `self.loop.run_forever()` and server creation with `asincio` that is already handled by gunicorn.

`bot.run()` could call `bot.start_app()` and handle the additional steps to run the development server

I'd suggest an usage like:

```python
#! /usr/bin/env python
from bottery import Bottery

SERVER_PORT = 7000

bot = Bottery(settings_module="mysettings")

@bot.patterns.regex('^.*$')
def parrot(message):
    return message

if __name__ == '__main__':
    bot.run(server_port=SERVER_PORT)
else:
    bot.start_app()
```

**Comment by romulocollopy** [comment]
@rougeth if you agree with this approach, please assingn me to the issue that I'll prepare a PR

**Comment by rougeth** [comment]
@romulocollopy how the gunicorn handles the server creation? this is one of the parts we don't need, right? https://github.com/rougeth/bottery/blob/master/bottery/bottery.py#L85-L91

I believe this change should be fine! 👍

**Comment by rougeth** [comment]
We now have a `wsgi.py` file to serve the projects using Bottery. It isn't on docs yet, but it's on the checklist at https://github.com/rougeth/bottery/issues/143.
