### ISSUE TITLE
Introduction page

### ISSUE THREAD

**Issue by rougeth** [rougeth/bottery#16]

**Comment by HargovindArora** [comment]
@rougeth where you want to this to be. Can you be more specific what has to be written in it?

**Comment by rougeth** [comment]
@HargovindArora I'll merge #15 until the end of this week. This PR adds a `/docs` folder with Sphinx configured. I want to have more non technical informations about Bottery, like why it exists and the problems it aims to solve. I'll assign this to me since there's just a few things about it on README.md and lots on my head. But thanks for asking.

**Comment by rougeth** [comment]
@HargovindArora I'll reorganize the issues with the `hacktoberfest` later too.

**Comment by nicoddemus** [comment]
Is this issue still valid now that we have a `quickstart` session in the docs?
