### ISSUE TITLE
Windows testing?

### ISSUE THREAD

**Issue by nicoddemus** [rougeth/bottery#20]
Are you guys interested in testing on Windows automatically as well?

I volunteer to open a PR with the proper configuration, someone owner of the repository just have to create an account/team on https://www.appveyor.com. 😁

**Comment by rougeth** [comment]
Yes, definitely! I created the account, let me know if you need anything.

**Comment by nicoddemus** [comment]
Could you please go to settings/badges and get the URL of the code for "Branch sample markdown code"? I would like to include the badge to the README in the same PR.

**Comment by rougeth** [comment]
`[![Build status](https://ci.appveyor.com/api/projects/status/we3h64nj98vvxcre/branch/master?svg=true)](https://ci.appveyor.com/project/rougeth/bottery/branch/master)`

**Comment by nicoddemus** [comment]
Thanks, #21 is up.
