### ISSUE TITLE
Validate projects name before creating its folder

### ISSUE THREAD

**Issue by rougeth** [rougeth/bottery#31]
What should be a valid name? See Django as reference.
https://github.com/rougeth/bottery/blob/master/bottery/cli.py#L33

**Comment by asi7296** [comment]
I'd like to take this up. Validate the name before creating the project, else throw an exception and exit?

**Comment by asi7296** [comment]
I'd like to take this up. Validate the name before creating the project, else throw an exception and exit?

**Comment by angelbarrera92** [comment]
Django name must be valid package names. 
I can take this issue today :)

**Comment by angelbarrera92** [comment]
As PEP8 indicates:


    Modules should have short, all-lowercase names. Underscores can be used in the module name if it improves readability. Python packages should also have short, all-lowercase names, although the use of underscores is discouraged.

**Comment by asi7296** [comment]
I've just submitted a PR addressing this issue a few minutes ago. The CI tests are currently running. Sorry about the timing, I should've posted a message here first about taking the issue up.

**Comment by angelbarrera92** [comment]
Ouch. Im late!

**Comment by rougeth** [comment]
Thank you for your interest @angelbarrera92! Hope you're able to work on another issue :smile:

**Comment by jtemporal** [comment]
I'll take a go at this one =)
