### ISSUE TITLE
Doc how to create a bot on Telegram

### ISSUE THREAD

**Issue by rougeth** [rougeth/bottery#35]
Specify the steps at Telegram to create a new bot.

**Comment by supertassu** [comment]
Assign me to this. @rougeth

**Comment by rougeth** [comment]
Thanks @supertassu! Do you want discuss what should have on this doc before starting?

**Comment by supertassu** [comment]
If you want, that's fine to me. Easiest to me would be thru [Discord](https://discordapp.com/): supertassu#0036

**Comment by rougeth** [comment]
@supertassu I just would like to have something similar to Telegram Bots documentation: https://core.telegram.org/bots#6-botfather. Nothing too extended.

**Comment by supertassu** [comment]
Just submitted a PR.
