### ISSUE TITLE
Create test for bottery.log.ColoredFormatter

### ISSUE THREAD

**Issue by rougeth** [rougeth/bottery#44]

**Comment by delta9000** [comment]
I can take this.

**Comment by delta9000** [comment]
Turns out it's not too easy to get the log output with the formatting applied.  Testfixtures has a nice wrapper for logging that intercepts the records, so I fed them to your logformatter directly and compared the output to known good ANSI escape codes for the coloration.

**Comment by rougeth** [comment]
Closed on #52
