### ISSUE TITLE
Increase coverage for bottery/app.py

### ISSUE THREAD

**Issue by rougeth** [rougeth/bottery#45]
Missing lines: 45-56, 59-66, 38->45
*See Travis log to confirm the missing lines:* https://travis-ci.org/rougeth/bottery

**Comment by kplaube** [comment]
I'll try to solve this. :)

**Comment by rougeth** [comment]
Missing lines: 54->57

**Comment by kplaube** [comment]
@rougeth I'm pretty much sure that those lines are being tested. I'll take a new look in order to increase this to 100%.

**Comment by rougeth** [comment]
Thanks @kplaube!
