### ISSUE TITLE
Increase coverage for bottery/cli.py

### ISSUE THREAD

**Issue by rougeth** [rougeth/bottery#46]
Missing lines: 51-52
*See Travis log to confirm the missing lines:* https://travis-ci.org/rougeth/bottery

**Comment by anapaulagomes** [comment]
A good idea is to add `codecov` to the project. Each time someone sends a PR, the tool will generate a coverage report pointing if the coverage has increased or not. Also, you can see the coverage easily with a beautiful badge. :)

**Comment by rougeth** [comment]
Hey @anapaulagomes!! Thanks for the comment! :D Codecov is already configured and it blocks each pull request that decrease the coverage. I disabled the report on pull request comments because I personally don't like it, but it's working!
