### ISSUE TITLE
Pin requirements versions at setup.py before 0.0.1 release

### ISSUE THREAD

**Issue by rougeth** [rougeth/bottery#60]

**Comment by nicoddemus** [comment]
@rougeth what pins do you have in mind? "hard" pins (`requests==2.18.0`) or "requirement" pins (`requests>=2.16`), IOW, pinning because you depend on a feature available starting from a specific version of a package?

**Comment by rougeth** [comment]
"requirement" pins, I don't want to have Bottery broken because of a dependency changed.

**Comment by nicoddemus** [comment]
Sounds good. 👍

**Comment by ellisonleao** [comment]
Can we use [Pipfile](https://github.com/pypa/pipfile) instead or its just too soon?

**Comment by rougeth** [comment]
Closing this one here, cannot see why Pipfile would help us here.
