### ISSUE TITLE
Codecov always on "Waiting for status to be reported "

### ISSUE THREAD

**Issue by rougeth** [rougeth/bottery#70]

**Comment by nicoddemus** [comment]
I've noticed this happening on occasion as well... not sure what's causing it though.

**Comment by guidiego** [comment]
@nicoddemus @rougeth we had some problems with it in Tenfold too, we noticed that sometimes codecov had delay to process the new coverages entries (mainly when you have many concurrencies builds running and reporting)

**Comment by rougeth** [comment]
[codecov](https://codecov.io/gh/rougeth/bottery/list/master/bottery) and [pytest-cov](https://travis-ci.org/rougeth/bottery/builds/287812616) are showing different reports :/ (both on master)


<img width="944" alt="screen shot 2017-10-13 at 23 58 23" src="https://user-images.githubusercontent.com/431892/31572003-a545e49c-b072-11e7-83c9-f19be717a001.png">
<img width="1143" alt="screen shot 2017-10-13 at 23 57 52" src="https://user-images.githubusercontent.com/431892/31572005-a75a0966-b072-11e7-818a-ce1c359ce9e0.png">

**Comment by rougeth** [comment]
I believe that was fixed :)
