### ISSUE TITLE
Concentrate all dependencies at setup.py

### ISSUE THREAD

**Issue by rougeth** [rougeth/bottery#72]
We have some dependencies at `tox.ini` that are not at `setup.py` and others duplicated on both files. We should keep them at `setup.py` on `extras_require` except `codecov`, that should stay only on `tox.ini`.

**Comment by jtemporal** [comment]
Hi @rougeth have you seen any example of that in any other project?

I'd like to take a go at this one =)

**Comment by rougeth** [comment]
@jtemporal I'd search for how to install dependencies from setup.py on tox. Probably something like `deps = .[dev]` should work.
