### ISSUE TITLE
Problems with python throws

### ISSUE THREAD

**Issue by guidiego** [rougeth/bottery#79]
### Whats happen?
For any reason python does not throw any exception during `bottery run`

### How reproduce it?
In my case I'm testing some stuff that I've done in this PR: #78, so you can jump on my branch and do this steps:

- Guarantee that bottery are local `pip install -e ../bottery/path`
- Jump to my PR (or go to any function and force a error)
- You will se that bottery still running without alerts or logs

**Comment by rougeth** [comment]
@ivanbrasilico got the same issue, I'll work on this one as soon as possible.

**Comment by rougeth** [comment]
Reference: https://stackoverflow.com/questions/43207927/how-to-shutdown-the-loop-and-print-error-if-coroutine-raised-an-exception-with-a

**Comment by rougeth** [comment]
It seems to be bigger then I thought: https://github.com/python/asyncio/issues/397.

@mawkee have you ever got in this issue?

**Comment by ElSaico** [comment]
I'm facing this as well - and, sadly enough, the solutions presented don't seem to work...

**Comment by rougeth** [comment]
I couldn't reproduce the same issue in a simpler example. A `raise` on both `main` and `subtask` will print the error:

```python
import asyncio

async def subtask():
    print('subtask')
    # raise

async def main():
    print('main')
    # raise
    await asyncio.gather(subtask())
    await main()

loop = asyncio.get_event_loop()
loop.create_task(main())
loop.run_forever()
```

But in a view, if I do something like this, bottery won't show the error:

```python
def pong(message):
    raise
```

**Comment by IvanBrasilico** [comment]
Maybe the views must be assyncronous functions too.

**Comment by rougeth** [comment]
Dear friends, the problem was in the logger settings :/ Sorry for that hahahaha

![](https://media.giphy.com/media/LyJ6KPlrFdKnK/giphy.gif)
