### ISSUE TITLE
Allow more complex patterns (without context)

### ISSUE THREAD

**Issue by rougeth** [rougeth/bottery#81]
At Python Brasil, we talked a lot about how `Pattern` obj is so limited and how we could improve it. The main point of the discussion was how we could implement other "types" of patterns:

```python
patterns = [
    # 1)
    Pattern('ping', ping),
    RegexPattern(r'^ping \d*$', regex_ping), # "ping 123" would be accepted
    StartswithPattern('/ping', regex_ping), # "/ping bottery" would be accepted

    # 2) or
    Pattern('ping', ping),
    Pattern(r'^ping$', regex_ping, type='regex'),
    Pattern('/ping', regex_ping, type='startswidth'),

    # 3) or
    Pattern('ping', ping),
    Pattern(r'^ping$', regex_ping, validator=regex_validator),
    Pattern('/ping', regex_ping, validator=startswith_validator),
    # where regex_validator and startswith_validator are the checkers
]
```

I believe the second "kind of" pattern is the easiest for who will use Bottery. But I think we should discuss it better.

@nicoddemus @muriloviana @mawkee @ElSaico @leportella

**Comment by ElSaico** [comment]
I'm partial towards 2) as well, myself - though the available mappings for  `type` would need to be a configurable setting for extensiblity purposes.

As an aside, Django 2.0 is going to follow option 1), with the `path` and `re_path` functions:

https://docs.djangoproject.com/en/dev/releases/2.0/#simplified-url-routing-syntax

**Comment by nicoddemus** [comment]
I think 2) is more suitable, as it will be more flexible. For example, when we include NLP support the pattern constructor will probably be very different:

```python
NaturalPattern([PURPOSE.BUY, PURPOSE.PRODUCTS], purchase_products)
```

IOW, not all patterns will share the same "constructor". 

It will also allow external packages to easily add patterns themselves without the need for any special support from `bottery` other than a well defined interface that patterns should comply to.

**Comment by leportella** [comment]
@nicoddemus you said you prefer the second one, but your example seems to be equal to the first option.  Which one do you prefer? :D

**Comment by nicoddemus** [comment]
Oops sorry I meant the first one, with separate classes for each pattern. 😋

**Comment by muriloviana** [comment]
The option 2) looks pretty easy to understand and manage. However, I think the option 1) is more explicit and readable to Bottery users.

**Comment by muriloviana** [comment]
I really like the idea of keep only one Pattern, but I guess it looks too magical.

**Comment by mawkee** [comment]
I think I prefer the first option. This would give us more flexibility for extra attributes depending on the pattern class; for instance, it'd make sense for RegexPattern to be able to use named groups, but that would make zero sense for Pattern. It'd be easier for IDEs to show some hints based on the pattern class

Even though 2 could potentially be easier to implement, on the long run it could increase complexity.

**Comment by rougeth** [comment]
Wooh, internally, Django does something really similar with the third option:
https://github.com/django/django/blob/master/django/urls/conf.py

**Comment by mawkee** [comment]
I think it's actually similar to the first option. They implemented RoutePattern and RegexPattern, then created a partial to each one of them (path / re_path). In practice, for the common user, he'll use either one of those

**Comment by mawkee** [comment]
I can work on this as soon as you decide which approach you want done ;-)

**Comment by rougeth** [comment]
@mawkee well, let's try the first option :)

**Comment by IvanBrasilico** [comment]
A suggestion of a FlexiblePattern. User can pass any function to pre-process the message beffore comparing to pattern:

class FuncPattern(Pattern):
    '''Receives a function to preprocess the incoming message
    text before comparing it to the pattern.
    Allows use of regular expressions, selecting partial words for
    routing, etc'''
    def __init__(self, pattern, view, pre_process):
        self.pre_process = pre_process
        Pattern.__init__(self, pattern, view)

    def check(self, message):
        text, _ = self.pre_process(message.text)
        if text == self.pattern:
            return self.view
        return False


### A function, for example, similar to starts_with:
def two_tokens(text):
    '''Receives a text string, splits on first space, return
    first word of list/original sentence and the rest of the sentence
    '''
    lista = text.split(' ')
    return lista[0], " ".join(lista[1:])

def sum_function(message):
       _, number_list = two_tokens(message.text)
       mysum = 0
       for item in number_list:
            mysum += int(item)
       return str(mysum)
     

Usage:
    FuncPattern('\sum', sum_function, two_tokens),

User type on Bot:

/sum 1 2 3

Receives:

6

**Comment by IvanBrasilico** [comment]
Code on https://github.com/IvanBrasilico/LacreBot

**Comment by leportella** [comment]
I think that after the refactor this issue should be closed, since patterns changed drastically
