### ISSUE TITLE
Catch KeyboardInterrupt on app.run() and close session and loop

### ISSUE THREAD

**Issue by rougeth** [rougeth/bottery#88]
https://github.com/rougeth/bottery/blob/master/bottery/cli.py#L52-L57

**Comment by Kalaborative** [comment]
Hi,

> close session and loop

By this do you mean, restart the `app.run()` session? Just making sure. Thanks!

**Comment by guidiego** [comment]
@Kalaborative I think that he wants something like use `.close` method from asyncion.Event and aiohttp.Session. I wrote this code right now:

```
    def close(self):
        logger.debug('Closing session and loop events')
        self._session.close()
        self.loop.close()
```

**Comment by rougeth** [comment]
Yep, that is it @guidiego, `session` without `_` and calling this new method on `bottery.cli.run` after catching KeyboardInterrupt exception.

**Comment by rougeth** [comment]
@Kalaborative just remember to test it :)

**Comment by guidiego** [comment]
@rougeth could I handle that one? Or prefer waiting a couple of days?

**Comment by rougeth** [comment]
@guidiego nooo, go ahead my friend :)
