### ISSUE TITLE
Python 2.x support?

### ISSUE THREAD

**Issue by rougeth** [rougeth/bottery#9]

**Comment by nicoddemus** [comment]
IMHO you don't need to support Python 2.x for two reasons:

* You won't be able to use the very nice `async/await` syntax if you support Python 2.
* This is not a library that will be used in another applications, this is a framework to create bots so users don't have the same restrictions of a common library, where they would use the library together with their existing codebase. Here this does not apply, users will use the framework and code their bot from scratch.

**Comment by rougeth** [comment]
Agreed  @nicoddemus, thanks!
