### ISSUE TITLE
TelegramEngine reaches recursion limit after a while

### ISSUE THREAD

**Issue by ElSaico** [rougeth/bottery#91]
With #79 solved, it seems a couple issues were unearthed.

After a while, since Python lacks tail-recursion due to a design decision by Guido himself, those consecutive calls to `self.polling` end up hitting the runtime's recursion depth limit, throwing a `RecursionError` in the process.

Of course, the bot becomes inoperant after this.

**Comment by rougeth** [comment]
Thanks @ElSaico! Any suggestion on how to solve this?

**Comment by rougeth** [comment]
Fixed here: https://github.com/rougeth/bottery/blob/master/bottery/platform/telegram.py#L114
